package nahama.emptydim.core;

import cpw.mods.fml.common.ModMetadata;
import nahama.emptydim.EmptyDimCore;

public class EmptyDimInfoCore {
	/** MODの情報を登録する。 */
	public static void registerInfo(ModMetadata meta) {
		meta.modId = EmptyDimCore.MODID;
		meta.name = EmptyDimCore.MODNAME;
		meta.description = "This mod adds new dimension named \"Empty Dimension\".";
		meta.version = EmptyDimCore.VERSION;
		meta.url = "http://www63.atwiki.jp/akasatanahama/pages/116.html";
		meta.authorList.add("Akasata Nahama");
		meta.logoFile = "assets/emptydim/logo.png";
		meta.autogenerated = false;
	}
}
